### ISSUE TITLE
400 bad request when syncing a folder with images and other files

### ISSUE THREAD

**Issue by andyman1222** [LenAnderson/Syncurr#1]
I set up the application correctly to sync a folder containing mostly images, but also some other web files, and some folders. When I tried to sync the folder to an album, the program would come up with a 400 bad request error. I think this might be caused because of the non-image files, which could be fixed with an extension checker in the source code.

**Comment by andyman1222** [comment]
Update: I just copied the folder(s) I want to sync to a new directory on my computer and removed all non-image files, however the 400 server error still occurred.

**Comment by LenAnderson** [comment]
Syncurr already filters for extensions and only uploads jpg, gif, png, bmp. So that should really not be the issue.

What did you put as the album's ID? It has to be only the ID, not the full URL. So if the album URL is `http://imgur.com/a/asdf` your ID would be `asdf`.

**Comment by LenAnderson** [comment]
Three weeks with no replies. I'm going to close this.
