### ISSUE TITLE
502 bad gateway, photos won't upload to album

### ISSUE THREAD

**Issue by andyman1222** [LenAnderson/Syncurr#2]
I have [this album](http://imgur.com/a/MGdP3), which is public (but not shared to community). I am trying to upload via Syncurr to it, however it comes up with a "502 Bad gateway" error, which occurs with manual "sync now" and when it automatically tries to upload.. I can upload photos manually fine, however.

**Comment by LenAnderson** [comment]
A bad gateway error probably means that the imgur api (used by third party software like Syncurr to communicate with imgur) was down at the time. Does this still happen?

**Comment by andyman1222** [comment]
I am not sure how many times the automatic sync actually fails unless it
creates the window. While the error window is open, does the program still
sync or does it pause the process?

**Comment by LenAnderson** [comment]
The sync stops for that folder.

Say you have two folders A and B. Halfway through syncing A the error appears. The rest of A will be skipped and Syncurr will try to sync B.

The next time a sync starts (automatically or "sync now") Syncurr will of course try again to sync both A and B.
